# Generated by Django 2.1.3 on 2018-11-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='address',
        ),
        migrations.RemoveField(
            model_name='package',
            name='email',
        ),
    ]
