# Generated by Django 2.1.3 on 2018-11-18 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20181111_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='transitstage',
            name='package',
        ),
        migrations.DeleteModel(
            name='TransitStage',
        ),
        migrations.AddField(
            model_name='package',
            name='stage',
            field=models.ManyToManyField(to='packages.Stage'),
        ),
    ]
